### PR TITLE
Finalize tokio-service APIs for 0.1

### PR DESCRIPTION
**Pull request by aturon**
A bit of tidying up ahead of the 0.1 release:
- Drop `poll_ready` for now, given that we're uncertain about the
  overall backpressure story, and it can be added easily as a defaulted
  method later on. Backpressure should be a major goal in an upcoming
  release.
- Rename `SimpleService` to `FnService`, matching the `Fn*` traits.
- Rename `NewService::Item` to `NewService::Instance`, for greater
  clarity about their relationship.

cc @carllerche @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
👍

**Comment by carllerche** [comment]
Seems good to me, we can revisit back pressure soon.

**Comment by Kerollmops** [comment]
up ? 😺

**Comment by aturon** [comment]
I've updated, now using `FnService`.

**Comment by aturon** [comment]
@alexcrichton Can you merge if/when you're happy with the final naming here?

**Pull request merged**
